language: node_js
node_js:
  - "5"

services:
  - mysql

before_install:
  - npm update -g npm
  - npm cache clean

before_script:
  - chmod 0777 ./node_modules/.bin/mocha
  - mysql -e "create database IF NOT EXISTS questionenginejs_test;" -uroot
  - mysql -e "CREATE USER 'dev'@'localhost' IDENTIFIED BY 'development';" -uroot
  - mysql -e "GRANT ALL PRIVILEGES ON questionenginejs_test. * TO 'dev'@'localhost';" -uroot
